[tool.poetry]
name = "pytils"
version = "0.3.1"
description = ""
authors = ["temi4sh <temi4sh@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^4.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
